api_platform:

    mapping:
        paths: ['%kernel.project_dir%/config/packages/api/mapping']

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]

#    enable_swagger: true
#    enable_swagger_ui: true

#    enable_re_doc: true
#    enable_entrypoint: true
#    enable_docs: true
#    enable_profiler: true

    show_webby: false

    collection:
        pagination:
            items_per_page: '%env(int:API_PAGINATION_COUNT)%'
