App\Entity\Brand:
    attributes:
        code:
            groups:
                - 'container:read:item'
                - 'container:read:collection'
        label:
            groups:
                - 'container:read:item'
