App\Entity\Container:
    attributes:
        id:
            groups:
                - 'container:read:item'
                - 'container:read:collection'
        label:
            groups:
                - 'container:read:item'
                - 'container:read:collection'
        width:
            groups:
                - 'container:read:item'
        height:
            groups:
                - 'container:read:item'
        items:
            groups:
                - 'container:read:item'
#                - 'container:read:collection'
